// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDreums8xvE7bQvT7ydFDG1WsZsC8VnaMI',
    appId: '1:225042821103:web:f62533ac94bc18afad901a',
    messagingSenderId: '225042821103',
    projectId: 'rideoptionspk-f26ee',
    authDomain: 'rideoptionspk-f26ee.firebaseapp.com',
    databaseURL: 'https://rideoptionspk-f26ee-default-rtdb.firebaseio.com',
    storageBucket: 'rideoptionspk-f26ee.appspot.com',
    measurementId: 'G-C4ZGT5L0XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_HxcNJokUS_z1dBLraJM6awb23M2aGk',
    appId: '1:225042821103:android:14ec86782ee071fbad901a',
    messagingSenderId: '225042821103',
    projectId: 'rideoptionspk-f26ee',
    databaseURL: 'https://rideoptionspk-f26ee-default-rtdb.firebaseio.com',
    storageBucket: 'rideoptionspk-f26ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDT3yxhZKhVYdvkCrzvOr-fQPrFtk7YiI',
    appId: '1:225042821103:ios:28c3f7b3fdddd518ad901a',
    messagingSenderId: '225042821103',
    projectId: 'rideoptionspk-f26ee',
    databaseURL: 'https://rideoptionspk-f26ee-default-rtdb.firebaseio.com',
    storageBucket: 'rideoptionspk-f26ee.appspot.com',
    androidClientId: '225042821103-13uaj598i7pcofehedjf5h99dqnpun7i.apps.googleusercontent.com',
    iosBundleId: 'com.devaxis.rideoptions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDT3yxhZKhVYdvkCrzvOr-fQPrFtk7YiI',
    appId: '1:225042821103:ios:28c3f7b3fdddd518ad901a',
    messagingSenderId: '225042821103',
    projectId: 'rideoptionspk-f26ee',
    databaseURL: 'https://rideoptionspk-f26ee-default-rtdb.firebaseio.com',
    storageBucket: 'rideoptionspk-f26ee.appspot.com',
    androidClientId: '225042821103-13uaj598i7pcofehedjf5h99dqnpun7i.apps.googleusercontent.com',
    iosBundleId: 'com.devaxis.rideoptions',
  );
}
